--Q1
SELECT MAGV, HOTEN, PHAI, NGSINH
FROM GIAOVIEN
--Q2
SELECT MADT, TENDT, KINHPHI
FROM DETAI
--Q3
SELECT *
FROM GIAOVIEN
WHERE LUONG > 2000
--Q4
SELECT *
FROM GIAOVIEN
WHERE MABM = 'HTTT'
--Q5
SELECT *
FROM GIAOVIEN
WHERE MABM = 'HTTT' AND LUONG > 2000
--Q6
SELECT *
FROM BOMON
WHERE TRUONGBM IS NULL
--Q7
SELECT *
FROM BOMON
WHERE TRUONGBM IS NOT NULL
--Q8
SELECT MAGV, HOTEN, PHAI, NGSINH
FROM GIAOVIEN
WHERE LUONG > 2000
--Q9
SELECT DISTINCT MAGV
FROM THAMGIADT
WHERE THAMGIADT.MADT = '001' OR THAMGIADT.MADT = '002'
--Q10
SELECT DISTINCT MAGV
FROM THAMGIADT
WHERE THAMGIADT.MADT = '001'
INTERSECT
SELECT DISTINCT MAGV
FROM THAMGIADT
WHERE THAMGIADT.MADT = '002'
--Q11
SELECT DISTINCT MAGV
FROM THAMGIADT
WHERE THAMGIADT.MADT = '001'
EXCEPT
SELECT DISTINCT MAGV
FROM THAMGIADT
WHERE THAMGIADT.MADT = '002'
--Q12

--Q13

--Q14

--Q15

--Q16 
SELECT GV.MAGV, GV.HOTEN, GV.PHAI, GV.NGSINH, GV.MABM, BOMON.TENBM
FROM GIAOVIEN GV, BOMON
WHERE GV.MABM = BOMON.MABM
--Q17
SELECT GIAOVIEN.*
FROM GIAOVIEN, KHOA
WHERE KHOA.TRUONGKHOA = GIAOVIEN.MAGV
--Q18
SELECT BOMON.*, GIAOVIEN.HOTEN
FROM BOMON, GIAOVIEN
WHERE BOMON.TRUONGBM = GIAOVIEN.MAGV
--Q19
SELECT BOMON.*, GIAOVIEN.HOTEN
FROM BOMON
LEFT OUTER JOIN GIAOVIEN
ON BOMON.TRUONGBM = GIAOVIEN.MAGV
--Q20

--Q21
SELECT GIAOVIEN.MAGV, GIAOVIEN.HOTEN, GIAOVIEN.PHAI, GIAOVIEN.NGSINH
FROM GIAOVIEN, BOMON
WHERE BOMON.TENBM = N'Hệ thống thông tin' AND GIAOVIEN.MABM = BOMON.MABM
--Q22
SELECT DISTINCT GIAOVIEN.MAGV, GIAOVIEN.HOTEN
FROM DETAI, GIAOVIEN, THAMGIADT, CHUDE
WHERE CHUDE.TENCD = N'Quản lý giáo dục' AND CHUDE.MACD = DETAI.MACD
	AND (DETAI.CAPQL = N'Trường' OR DETAI.CAPQL = 'ĐHQG')
	AND DETAI.GVCNDT = GIAOVIEN.MAGV
--Q23
SELECT GV1.MAGV, GV1.HOTEN, GV1.NGSINH, GV2.HOTEN AS TEN_GVQLCM
FROM GIAOVIEN GV1, GIAOVIEN GV2
WHERE GV1.GVQLCM = GV2.MAGV
--Q24
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE (DT.TENDT = N'HTTT quản lý các trường ĐH' OR DT.TENDT = N'HTTT quản lý giáo vụ cho một Khoa')
	AND DT.MADT = TG.MADT AND GV.MAGV = TG.MAGV
--Q25
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE DT.TENDT = N'Ứng dụng hóa học xanh'
	AND DT.MADT = TG.MADT AND GV.MAGV = TG.MAGV
INTERSECT
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
	AND DT.MADT = TG.MADT AND GV.MAGV = TG.MAGV
--Q26
SELECT GIAOVIEN.MAGV, GIAOVIEN.HOTEN
FROM GIAOVIEN
WHERE NOT EXISTS (SELECT*
				  FROM THAMGIADT
				  WHERE GIAOVIEN.MAGV = THAMGIADT.MAGV)
--Q27
SELECT GV1.*
FROM GIAOVIEN GV1, GIAOVIEN GV2
WHERE GV1.GVQLCM = GV2.MAGV AND GV2.DIACHI <> GV1.DIACHI -- DIACHI = THANHPHO
--Q28

--Q29
SELECT COUNT(*) AS SL_GV
FROM GIAOVIEN
--Q30
SELECT GIAOVIEN.MABM, BOMON.TENBM, COUNT(*) SL_GV
FROM BOMON, GIAOVIEN
WHERE GIAOVIEN.MABM = BOMON.MABM
GROUP BY GIAOVIEN.MABM, BOMON.TENBM