--Q1
SELECT MASV, HOTEN, PHAI, NGAYSINH
FROM SINHVIEN

--Q2
SELECT MASV, HOTEN, PHAI, NGAYSINH
FROM SINHVIEN, NGANH
WHERE NGANH.TENNGANH = N'Hệ thống thông tin' AND NGANH.MANGANH = SINHVIEN.MANGANH

--Q3
SELECT NGANH.MANGANH, NGANH.TENNGANH
FROM NGANH
WHERE NGANH.TSSV > 200

--Q4
SELECT*
FROM CHUYENDE
WHERE CHUYENDE.SOSVTD <= 100

--Q5
SELECT CD.MACD, CD.TENCD
FROM CHUYENDE CD, NGANH, CD_NGANH CDN
WHERE CDN.MANGANH = NGANH.MANGANH AND NGANH.TENNGANH = N'Mạng máy tính' AND CD.MACD = CDN.MACD

--Q6
SELECT CD.MACD, CD.TENCD, COUNT(*) AS SO_NGANH
FROM CHUYENDE CD, CD_NGANH
WHERE CD.MACD = CD_NGANH.MACD
GROUP BY CD.MACD, CD.TENCD

--Q7
SELECT SV.MASV, SV.HOTEN
FROM SINHVIEN SV, DANGKY DK, CHUYENDE CD
WHERE CD.TENCD = 'Java' AND CD.MACD = DK.MACD AND SV.MASV = DK.MASV
GROUP BY SV.MASV, SV.HOTEN
HAVING COUNT(DK.MACD) > 1

--Q8
SELECT DISTINCT SINHVIEN.*
FROM SINHVIEN, NGANH, DANGKY,CHUYENDE
WHERE NGANH.TENNGANH = N'Hệ thống thông tin' AND SINHVIEN.MANGANH = NGANH.MANGANH 
AND SINHVIEN.MASV = DANGKY.MASV AND CHUYENDE.TENCD = 'Oracle' AND CHUYENDE.MACD = DANGKY.MACD

--Q9
SELECT NGANH.MANGANH, NGANH.TENNGANH
FROM NGANH
WHERE NGANH.SOCD > 2

--Q10
SELECT SV.MASV, SV.HOTEN
FROM SINHVIEN SV, DANGKY DK
WHERE SV.MASV = DK.MASV AND DK.HOCKY = 1 AND DK.NAM = 2009
GROUP BY SV.MASV, SV.HOTEN
HAVING COUNT(DK.MACD) > 2

--Q11
SELECT NGANH.*
FROM NGANH, CHUYENDE, CD_NGANH
WHERE (CHUYENDE.TENCD = 'Java' OR CHUYENDE.TENCD = 'Oracle') AND CHUYENDE.MACD = CD_NGANH.MACD
		AND CD_NGANH.MANGANH = NGANH.MANGANH

--Q12
SELECT NGANH.*
FROM NGANH, CHUYENDE, CD_NGANH
WHERE CHUYENDE.TENCD = 'Java' AND CHUYENDE.MACD = CD_NGANH.MACD
		AND CD_NGANH.MANGANH = NGANH.MANGANH
INTERSECT
SELECT NGANH.*
FROM NGANH, CHUYENDE, CD_NGANH
WHERE CHUYENDE.TENCD = 'Oracle' AND CHUYENDE.MACD = CD_NGANH.MACD
		AND CD_NGANH.MANGANH = NGANH.MANGANH

--Q13
SELECT NGANH.*
FROM NGANH, CHUYENDE, CD_NGANH
WHERE CHUYENDE.TENCD = 'Java' AND CHUYENDE.MACD = CD_NGANH.MACD
		AND CD_NGANH.MANGANH = NGANH.MANGANH
EXCEPT
SELECT NGANH.*
FROM NGANH, CHUYENDE, CD_NGANH
WHERE CHUYENDE.TENCD = 'Oracle' AND CHUYENDE.MACD = CD_NGANH.MACD
		AND CD_NGANH.MANGANH = NGANH.MANGANH

--Q14 ---------- MÃ LÀ 0012345
SELECT DISTINCT CHUYENDE.*
FROM CHUYENDE, DANGKY
WHERE DANGKY.MASV = '002' AND DANGKY.MACD = CHUYENDE.MACD

--Q15
CREATE VIEW SVDK AS
SELECT SV.MASV
FROM SINHVIEN SV, DANGKY DK
WHERE SV.MASV = DK.MASV AND DK.HOCKY = 1 AND DK.NAM = 2004
GROUP BY SV.MASV
HAVING COUNT(DK.MACD) = 2
SELECT SINHVIEN.*
FROM SINHVIEN
JOIN SVDK
ON SINHVIEN.MASV = SVDK.MASV
--Q16
CREATE VIEW SVDK AS
SELECT SV.MASV
FROM SINHVIEN SV, DANGKY DK
WHERE SV.MASV = DK.MASV AND DK.HOCKY = 1 AND DK.NAM = 2004 AND DK.DIEM = N'Đạt'
GROUP BY SV.MASV
HAVING COUNT(DK.MACD) = 2
SELECT SINHVIEN.*
FROM SINHVIEN
JOIN SVDK
ON SINHVIEN.MASV = SVDK.MASV

--Q17
CREATE VIEW SVDK AS
SELECT DISTINCT SV.MASV
FROM SINHVIEN SV, DANGKY DK, NGANH
WHERE NGANH.TENNGANH = N'Hệ thống thông tin' AND SV.MASV = DK.MASV AND SV.MANGANH = NGANH.MANGANH
	AND NOT EXISTS (SELECT MACD
					FROM CD_NGANH CDN, NGANH N
					WHERE N.TENNGANH = N'Hệ thống thông tin' AND CDN.MANGANH = N.MANGANH 
					EXCEPT
					SELECT DK1.MACD
					FROM DANGKY DK1
					WHERE DK.MASV = DK1.MASV)
SELECT SV.*
FROM SINHVIEN SV
JOIN SVDK
ON SV.MASV = SVDK.MASV


--Q18
CREATE VIEW SVDK AS
SELECT SV.MASV
FROM SINHVIEN SV, DANGKY DK
WHERE SV.MASV = DK.MASV AND DK.NAM = 2005
GROUP BY SV.MASV
HAVING COUNT(DK.MACD) > 1 
SELECT SINHVIEN.*
FROM SINHVIEN
JOIN SVDK
ON SINHVIEN.MASV = SVDK.MASV

--Q19
SELECT SV.*
FROM NGANH N, CHUYENDE CD, SINHVIEN SV, DANGKY DK
WHERE N.TENNGANH = N'Hệ thống thông tin' AND SV.MANGANH = N.MANGANH
	AND CD.TENCD = 'Oracle' AND CD.MACD = DK.MACD AND SV.MASV = DK.MASV AND DK.NAM = 2005
EXCEPT
SELECT SV.*
FROM NGANH N, CHUYENDE CD, SINHVIEN SV, DANGKY DK
WHERE N.TENNGANH = N'Hệ thống thông tin' AND SV.MANGANH = N.MANGANH
	AND CD.TENCD = 'CSDL phân tán' AND CD.MACD = DK.MACD AND SV.MASV = DK.MASV AND DK.NAM = 2005

--Q20
SELECT NGANH.MANGANH, NGANH.TENNGANH, NGANH.TSSV
FROM NGANH

--Q21
SELECT DK.MASV, DK.MACD, DK.HOCKY, DK.NAM
FROM NGANH N, DANGKY DK, SINHVIEN SV
WHERE N.TENNGANH = N'Hệ thống thông tin' AND N.MANGANH = SV.MANGANH AND SV.MASV = DK.MASV
	AND DK.HOCKY = 1 AND DK.NAM = 2010
	AND NOT EXISTS (SELECT MACD
					FROM CD_NGANH
					WHERE CD_NGANH.MANGANH = N.MANGANH
					EXCEPT
					SELECT DK1.MACD
					FROM DANGKY DK1, CD_NGANH CND
					WHERE DK1.MASV = DK.MASV AND DK1.MACD = CND.MACD AND CND.MANGANH = N.MANGANH)

--Q22
SELECT SV.*
FROM SINHVIEN SV
WHERE NOT EXISTS (SELECT*
				FROM DANGKY DK
				WHERE SV.MASV = DK.MASV)

--Q23
SELECT DISTINCT CDM.HOCKY, CDM.NAM
FROM CD_MO CDM, NGANH N
WHERE N.TENNGANH = N'Hệ thống thông tin' 
AND NOT EXISTS (SELECT CDN.MACD
				FROM CD_NGANH CDN
				WHERE CDN.MANGANH = N.MANGANH
				EXCEPT
				SELECT CDM1.MACD
				FROM CD_MO CDM1
				WHERE CDM1.HOCKY = CDM.HOCKY AND CDM1.NAM = CDM.NAM)
--Q24 --------------- MASV LA 0012345
SELECT DISTINCT CD.MACD, CD.TENCD
FROM CHUYENDE CD
WHERE CD.MACD IN (SELECT CDN.MACD
				FROM CD_NGANH CDN, SINHVIEN SV
				WHERE SV.MASV = '006' AND CDN.MANGANH = SV.MANGANH
				EXCEPT
				SELECT DK1.MACD
				FROM DANGKY DK1
				WHERE DK1.MASV = '006')

--Q25
CREATE VIEW SVDK AS
SELECT SV.MASV
FROM NGANH N, DANGKY DK, SINHVIEN SV
WHERE N.TENNGANH = N'Hệ thống thông tin' AND N.MANGANH = SV.MANGANH AND DK.HOCKY = 1 
	AND DK.NAM = 2005 AND SV.MASV = DK.MASV
GROUP BY SV.MASV
HAVING COUNT(DK.MACD) = 1
SELECT SV.*
FROM SINHVIEN SV
JOIN SVDK
ON SV.MASV = SVDK.MASV

--Q26
SELECT CD.TENCD
FROM CHUYENDE CD
WHERE NOT EXISTS (SELECT NGANH.MANGANH
				FROM NGANH
				EXCEPT
				SELECT CDN.MANGANH
				FROM CD_NGANH CDN
				WHERE CDN.MACD = CD.MACD)
--Q27
SELECT DISTINCT CDN.*
FROM CD_NGANH CDN, CD_MO CDM, NGANH N
WHERE CDM.HOCKY = 1 AND CDM.NAM = 2005 AND N.TENNGANH = N'Mạng máy tính' AND N.MANGANH = CDN.MANGANH
	AND CDM.MACD = CDN.MACD

--Q28
SELECT CD.*
FROM CD_NGANH CDN, NGANH N, CHUYENDE CD
WHERE CDN.MANGANH = N.MANGANH AND N.TENNGANH = N'Hệ thống thông tin' AND CD.MACD = CDN.MACD
INTERSECT 
SELECT CD.*
FROM CD_NGANH CDN, NGANH N, CHUYENDE CD
WHERE CDN.MANGANH = N.MANGANH AND N.TENNGANH = N'Công nghệ tri thức' AND CD.MACD = CDN.MACD

--Q29
CREATE VIEW CHUAHOCLAI AS
SELECT SV.MASV
FROM SINHVIEN SV
EXCEPT
SELECT DK.MASV
FROM DANGKY DK
GROUP BY DK.MASV, DK.MACD
HAVING COUNT(DK.DIEM) >= 2

SELECT SV.*
FROM SINHVIEN SV
JOIN CHUAHOCLAI
ON SV.MASV = CHUAHOCLAI.MASV
