--Q1
SELECT MAGV, HOTEN, PHAI, NGSINH
FROM GIAOVIEN
--Q2
SELECT MADT, TENDT, KINHPHI
FROM DETAI
--Q3
SELECT *
FROM GIAOVIEN
WHERE LUONG > 2000
--Q4
SELECT *
FROM GIAOVIEN
WHERE MABM = 'HTTT'
--Q5
SELECT *
FROM GIAOVIEN
WHERE MABM = 'HTTT' AND LUONG > 2000
--Q6
SELECT *
FROM BOMON
WHERE TRUONGBM IS NULL
--Q7
SELECT *
FROM BOMON
WHERE TRUONGBM IS NOT NULL
--Q8
SELECT MAGV, HOTEN, PHAI, NGSINH
FROM GIAOVIEN
WHERE LUONG > 2000
--Q9
SELECT DISTINCT MAGV
FROM THAMGIADT
WHERE THAMGIADT.MADT = '001' OR THAMGIADT.MADT = '002'
--Q10
SELECT DISTINCT MAGV
FROM THAMGIADT
WHERE THAMGIADT.MADT = '001'
INTERSECT
SELECT DISTINCT MAGV
FROM THAMGIADT
WHERE THAMGIADT.MADT = '002'
--Q11
SELECT DISTINCT MAGV
FROM THAMGIADT
WHERE THAMGIADT.MADT = '001'
EXCEPT
SELECT DISTINCT MAGV
FROM THAMGIADT
WHERE THAMGIADT.MADT = '002'
--Q12
SELECT DISTINCT GV.MAGV, TG.MADT, TG.STT
FROM GIAOVIEN GV, DETAI DT, THAMGIADT TG
WHERE GV.MABM = 'HTTT' AND GV.MAGV = TG.MAGV AND DT.CAPQL = N'Trường' AND DT.MADT = TG.MADT
	AND NOT EXISTS ((SELECT CV.SOTT
					FROM CONGVIEC CV
					WHERE CV.MADT = DT.MADT AND DT.CAPQL = N'Trường')
					EXCEPT
					(SELECT TG2.STT
					FROM THAMGIADT TG2
					WHERE TG2.MAGV = TG.MAGV AND TG2.MADT = TG.MADT))
--Q13
SELECT DISTINCT GV.*
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MABM = 'MMT' AND GV.MAGV = TG.MAGV AND TG.MADT = '001'
	AND NOT EXISTS ((SELECT CV.SOTT
					FROM CONGVIEC CV
					WHERE CV.MADT = '001')
					EXCEPT
					(SELECT TG2.STT
					FROM THAMGIADT TG2
					WHERE TG2.MAGV = TG.MAGV AND TG2.MADT = '001'))

--Q14
SELECT DISTINCT GV.*
FROM GIAOVIEN GV, BOMON BM, THAMGIADT TG, DETAI DT
WHERE BM.TENBM = N'Mạng Máy Tính' AND GV.MABM = BM.MABM AND GV.MAGV = TG.MAGV AND DT.TENDT = N'Ứng dụng hóa học xanh' AND TG.MADT = DT.MADT
	AND NOT EXISTS ((SELECT CV.SOTT
					FROM CONGVIEC CV
					WHERE CV.MADT = DT.MADT AND DT.TENDT = N'Ứng dụng hóa học xanh')
					EXCEPT
					(SELECT TG2.STT
					FROM THAMGIADT TG2
					WHERE TG2.MAGV = TG.MAGV AND DT.TENDT = N'Ứng dụng hóa học xanh' AND TG2.MADT = DT.MADT))

--Q15
SELECT DISTINCT GV.*
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = '003' AND TG.MAGV = '003' AND TG.MADT = '001'
	AND NOT EXISTS ((SELECT CV.SOTT
					FROM CONGVIEC CV
					WHERE CV.MADT = '001')
					EXCEPT
					(SELECT TG2.STT
					FROM THAMGIADT TG2
					WHERE TG2.MAGV = '003' AND TG2.MADT = '001'))

--Q16 
SELECT GV.MAGV, GV.HOTEN, GV.PHAI, GV.NGSINH, GV.MABM, BOMON.TENBM
FROM GIAOVIEN GV, BOMON
WHERE GV.MABM = BOMON.MABM
--Q17
SELECT GIAOVIEN.*
FROM GIAOVIEN, KHOA
WHERE KHOA.TRUONGKHOA = GIAOVIEN.MAGV
--Q18
SELECT BOMON.*, GIAOVIEN.HOTEN
FROM BOMON, GIAOVIEN
WHERE BOMON.TRUONGBM = GIAOVIEN.MAGV
--Q19
SELECT BOMON.*, GIAOVIEN.HOTEN
FROM BOMON
LEFT OUTER JOIN GIAOVIEN
ON BOMON.TRUONGBM = GIAOVIEN.MAGV
--Q20
SELECT DISTINCT GV.MAGV, GV.HOTEN, TG.MADT, TG.STT, CV.TENCV, DT.TENDT
FROM GIAOVIEN GV
LEFT JOIN ((THAMGIADT TG JOIN DETAI DT
		ON TG.MADT = DT.MADT)
		JOIN CONGVIEC CV
		ON TG.MADT = CV.MADT AND TG.STT = CV.SOTT)
ON GV.MAGV = TG.MAGV
--Q21
SELECT GIAOVIEN.MAGV, GIAOVIEN.HOTEN, GIAOVIEN.PHAI, GIAOVIEN.NGSINH
FROM GIAOVIEN, BOMON
WHERE BOMON.TENBM = N'Hệ thống thông tin' AND GIAOVIEN.MABM = BOMON.MABM
--Q22
SELECT DISTINCT GIAOVIEN.MAGV, GIAOVIEN.HOTEN
FROM DETAI, GIAOVIEN, THAMGIADT, CHUDE
WHERE CHUDE.TENCD = N'Quản lý giáo dục' AND CHUDE.MACD = DETAI.MACD
	AND (DETAI.CAPQL = N'Trường' OR DETAI.CAPQL = 'ĐHQG')
	AND DETAI.GVCNDT = GIAOVIEN.MAGV
--Q23
SELECT GV1.MAGV, GV1.HOTEN, GV1.NGSINH, GV2.HOTEN AS TEN_GVQLCM
FROM GIAOVIEN GV1, GIAOVIEN GV2
WHERE GV1.GVQLCM = GV2.MAGV
--Q24
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE (DT.TENDT = N'HTTT quản lý các trường ĐH' OR DT.TENDT = N'HTTT quản lý giáo vụ cho một Khoa')
	AND DT.MADT = TG.MADT AND GV.MAGV = TG.MAGV
--Q25
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE DT.TENDT = N'Ứng dụng hóa học xanh'
	AND DT.MADT = TG.MADT AND GV.MAGV = TG.MAGV
INTERSECT
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
	AND DT.MADT = TG.MADT AND GV.MAGV = TG.MAGV
--Q26
SELECT GIAOVIEN.MAGV, GIAOVIEN.HOTEN
FROM GIAOVIEN
WHERE NOT EXISTS (SELECT*
				  FROM THAMGIADT
				  WHERE GIAOVIEN.MAGV = THAMGIADT.MAGV)
--Q27
SELECT GV1.*
FROM GIAOVIEN GV1, GIAOVIEN GV2
WHERE GV1.GVQLCM = GV2.MAGV AND GV2.DIACHI <> GV1.DIACHI -- DIACHI = THANHPHO
--Q28
SELECT DISTINCT GV.*
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV AND TG.MADT = '001'
	AND NOT EXISTS ((SELECT CV.SOTT
					FROM CONGVIEC CV
					WHERE CV.MADT = '001')
					EXCEPT
					(SELECT TG2.STT
					FROM THAMGIADT TG2
					WHERE TG2.MAGV = TG.MAGV AND TG2.MADT = '001'))
--Q29
SELECT COUNT(*) AS SL_GV
FROM GIAOVIEN
--Q30
SELECT GIAOVIEN.MABM, BOMON.TENBM, COUNT(*) SL_GV
FROM BOMON, GIAOVIEN
WHERE GIAOVIEN.MABM = BOMON.MABM
GROUP BY GIAOVIEN.MABM, BOMON.TENBM
--Q31
SELECT GIAOVIEN.MABM, BOMON.TENBM, COUNT(*) SL_GV
FROM BOMON, GIAOVIEN
WHERE GIAOVIEN.MABM = BOMON.MABM AND YEAR(GIAOVIEN.NGSINH) < 1975
GROUP BY GIAOVIEN.MABM, BOMON.TENBM
--Q32
SELECT GIAOVIEN.MABM, BOMON.TENBM, COUNT(*) SL_GV_Nu
FROM BOMON, GIAOVIEN
WHERE GIAOVIEN.MABM = BOMON.MABM AND GIAOVIEN.PHAI = N'Nữ' 
GROUP BY GIAOVIEN.MABM, BOMON.TENBM
HAVING COUNT(*) > 5
--Q33
SELECT COUNT(*) AS SL_DETAI
FROM DETAI
WHERE YEAR(DETAI.NGAYBD) BETWEEN 2007 AND 2010
--Q34
INSERT INTO THAMGIADT(MAGV, MADT, STT)
SELECT DISTINCT '003', CV.MADT, CV.SOTT
FROM CONGVIEC CV
WHERE CV.MADT = '001' AND CV.SOTT IN ((SELECT CV1.SOTT
									FROM CONGVIEC CV1
									WHERE CV1.MADT = '001')
									EXCEPT
									(SELECT TG.STT
									FROM THAMGIADT TG
									WHERE TG.MAGV = '003' AND TG.MADT = '001'))
--Q35
DELETE FROM THAMGIADT
WHERE THAMGIADT.MADT = '002'
--Q36
UPDATE GIAOVIEN
SET LUONG = LUONG*1.5
WHERE GIAOVIEN.MABM = 'HTTT'
--Q37
UPDATE THAMGIADT
SET PHUCAP = 2
WHERE THAMGIADT.MADT = '006'
	
---------------------- BÀI 3
--Q1
SELECT DISTINCT GIAOVIEN.MAGV, GIAOVIEN.HOTEN
FROM GIAOVIEN, BOMON, KHOA
WHERE GIAOVIEN.MAGV = BOMON.TRUONGBM OR GIAOVIEN.MAGV = KHOA.TRUONGKHOA
--Q2
SELECT GV1.MAGV, GV1.HOTEN, GV2.MAGV AS MAGVQL, GV2.HOTEN AS TENGVQL
FROM GIAOVIEN GV1, GIAOVIEN GV2
WHERE GV1.GVQLCM = GV2.MAGV AND GV1.NGSINH = GV2.NGSINH
--Q3
SELECT GIAOVIEN.MAGV, GIAOVIEN.HOTEN
FROM GIAOVIEN, BOMON
WHERE BOMON.TENBM = N'Hệ thống thông tin' AND BOMON.MABM = GIAOVIEN.MABM 
										  AND  NOT EXISTS (SELECT*
														   FROM THAMGIADT
														   WHERE THAMGIADT.MAGV = GIAOVIEN.MAGV)
--Q4
SELECT DISTINCT KHOA.TENKHOA
FROM KHOA, BOMON
WHERE BOMON.MAKHOA = KHOA.MAKHOA
GROUP BY KHOA.TENKHOA
HAVING COUNT(BOMON.MABM) >= ALL(SELECT COUNT(BOMON.MABM)
								FROM BOMON, KHOA
								WHERE BOMON.MAKHOA = KHOA.MAKHOA
								GROUP BY KHOA.TENKHOA)
--Q5 --------------------------------- CÓ VẤN ĐỀ
SELECT DISTINCT DT.TENDT, GV.HOTEN, SUM(TG.PHUCAP) AS PHUCAP_MAX
FROM THAMGIADT TG, DETAI DT, GIAOVIEN GV
WHERE GV.MAGV = TG.MAGV AND TG.MADT = DT.MADT
GROUP BY DT.TENDT, GV.HOTEN
HAVING SUM(TG.PHUCAP) IS NOT NULL 
	AND SUM(TG.PHUCAP) >= ALL(SELECT SUM(TG.PHUCAP)
							FROM THAMGIADT TG, GIAOVIEN GV, DETAI DT
							WHERE GV.MAGV = TG.MAGV AND TG.MADT = DT.MADT
							GROUP BY DT.TENDT, GV.HOTEN
							HAVING SUM(TG.PHUCAP) IS NOT NULL)
--Q6
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV, KHOA K
WHERE K.TRUONGKHOA = GV.MAGV AND (DATEDIFF(D, GETDATE(), GV.NGSINH)) >= ALL(SELECT DATEDIFF(D, GETDATE(), GV.NGSINH)
																			FROM GIAOVIEN GV, KHOA K
																			WHERE K.TRUONGKHOA = GV.MAGV)