--Q1
SELECT DISTINCT TT.TENTT
FROM THUYTHU TT, DANGKY DK
WHERE DK.MATAU = '103' AND DK.MATT = TT.MATT

--Q2
SELECT DISTINCT TENTT
FROM THUYTHU
WHERE BAC > 7

--Q3
SELECT DISTINCT TENTT, TUOI
FROM THUYTHU
WHERE BAC > 7

--Q4
SELECT DISTINCT TT.TENTT, TAU.TENTAU, DK.NGAY
FROM THUYTHU TT, TAU, DANGKY DK
WHERE DK.MATT = TT.MATT AND DK.MATAU = TAU.MATAU

--Q5
SELECT DISTINCT TT.TENTT
FROM THUYTHU TT, TAU, DANGKY DK
WHERE DK.MATT = TT.MATT AND DK.MATAU = TAU.MATAU AND TAU.MAU = N'Đỏ'

--Q6
SELECT DISTINCT TAU.MAU
FROM THUYTHU TT, TAU, DANGKY DK
WHERE DK.MATT = TT.MATT AND DK.MATAU = TAU.MATAU AND TT.TENTT = N'Hùng'

--Q7
SELECT DISTINCT TT.TENTT
FROM THUYTHU TT
WHERE EXISTS (SELECT*
			FROM DANGKY DK
			WHERE DK.MATT = TT.MATT)

--Q8
SELECT DISTINCT TT.TENTT
FROM THUYTHU TT
WHERE EXISTS (SELECT*
			FROM DANGKY DK, TAU
			WHERE DK.MATT = TT.MATT AND DK.MATAU = TAU.MATAU AND (TAU.MAU = N'Đỏ' OR TAU.MAU = N'Xanh'))

--Q9
SELECT DISTINCT TT.TENTT
FROM THUYTHU TT
WHERE EXISTS (SELECT*
			FROM DANGKY DK, TAU
			WHERE DK.MATT = TT.MATT AND DK.MATAU = TAU.MATAU AND TAU.MAU = N'Đỏ')
INTERSECT
SELECT DISTINCT TT.TENTT
FROM THUYTHU TT
WHERE EXISTS (SELECT*
			FROM DANGKY DK, TAU
			WHERE DK.MATT = TT.MATT AND DK.MATAU = TAU.MATAU AND TAU.MAU = N'Xanh')

--Q10
SELECT DISTINCT TT.TENTT
FROM THUYTHU TT, DANGKY DK
WHERE TT.MATT = DK.MATT 
GROUP BY TT.MATT, TT.TENTT
HAVING COUNT(*) >= 2

--Q11
SELECT TT.MATT
FROM THUYTHU TT
WHERE TT.TUOI > 20 AND NOT EXISTS (SELECT*
								FROM DANGKY DK, TAU
								WHERE TT.MATT = DK.MATT AND DK.MATAU = TAU.MATAU AND TAU.MAU = N'Đỏ')

--Q12
SELECT DISTINCT TT.TENTT
FROM THUYTHU TT, DANGKY DK
WHERE TT.MATT = DK.MATT
	AND NOT EXISTS (SELECT TAU.MATAU
					FROM TAU
					EXCEPT
					SELECT DK1.MATAU
					FROM DANGKY DK1
					WHERE DK1.MATT = DK.MATT)

--Q13
SELECT DISTINCT TT.TENTT
FROM THUYTHU TT, DANGKY DK
WHERE TT.MATT = DK.MATT
	AND NOT EXISTS (SELECT TAU.MATAU
					FROM TAU
					WHERE TAU.TENTAU = N'Marine'
					EXCEPT
					SELECT DK1.MATAU
					FROM DANGKY DK1
					WHERE DK1.MATT = DK.MATT)

--Q14
SELECT DISTINCT TT.TENTT
FROM THUYTHU TT, DANGKY DK
WHERE TT.MATT = DK.MATT
	AND NOT EXISTS (SELECT TAU.MATAU
					FROM TAU
					WHERE TAU.MAU = N'Đỏ'
					EXCEPT
					SELECT DK1.MATAU
					FROM DANGKY DK1
					WHERE DK1.MATT = DK.MATT)
