-- Q58. Cho biết tên giáo viên nào mà tham gia đề tài đủ tất cả các chủ đề.
-- EXCEPT
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG1
WHERE GV.MAGV = TG1.MAGV 
	AND NOT EXISTS (SELECT CD.MACD
					FROM CHUDE CD
					EXCEPT
					SELECT CD2.MACD
					FROM THAMGIADT TG2, DETAI DT2, CHUDE CD2
					WHERE TG2.MAGV = TG1.MAGV 
						AND TG2.MADT = DT2.MADT
						AND DT2.MACD = CD2.MACD)

-- NOT EXISTS
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG1
WHERE GV.MAGV = TG1.MAGV 
	AND NOT EXISTS (SELECT*
					FROM CHUDE CD1
					WHERE NOT EXISTS (SELECT*
									FROM THAMGIADT TG2, DETAI DT2, CHUDE CD2
									WHERE CD2.MACD = CD1.MACD
										AND TG2.MAGV = TG1.MAGV 
										AND TG2.MADT = DT2.MADT
										AND DT2.MACD = CD2.MACD))
-- COUNT	
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG1, DETAI DT1, CHUDE CD1
WHERE GV.MAGV = TG1.MAGV
	AND TG1.MADT = DT1.MADT
	AND DT1.MACD = CD1.MACD
GROUP BY GV.HOTEN, TG1.MAGV
HAVING COUNT(DISTINCT CD1.MACD) = (SELECT COUNT(*)
								FROM CHUDE)

-- Q59. Cho	biết tên đề tài	nào	mà được tất	cả các giáo	viên của bộ môn	HTTT tham gia.
-- EXCEPT
SELECT DISTINCT DT1.TENDT
FROM DETAI DT1, THAMGIADT TG1
WHERE TG1.MADT = DT1.MADT
	AND NOT EXISTS (SELECT GV2.MAGV
					FROM GIAOVIEN GV2
					WHERE GV2.MABM = 'HTTT'
					EXCEPT
					SELECT TG2.MAGV
					FROM THAMGIADT TG2
					WHERE TG2.MADT = TG1.MADT)

-- NOT EXISTS
SELECT DISTINCT DT1.TENDT
FROM DETAI DT1, THAMGIADT TG1
WHERE TG1.MADT = DT1.MADT
	AND NOT EXISTS (SELECT*
					FROM GIAOVIEN GV2
					WHERE GV2.MABM = 'HTTT'
						AND NOT EXISTS (SELECT*
									FROM THAMGIADT TG2
									WHERE TG2.MADT = TG1.MADT
										AND TG2.MAGV = GV2.MAGV))
-- COUNT
SELECT DT1.TENDT 
FROM DETAI DT1, THAMGIADT TG1, GIAOVIEN GV1
WHERE DT1.MADT = TG1.MADT
	AND GV1.MABM = 'HTTT'
	AND GV1.MAGV = TG1.MAGV
GROUP BY DT1.TENDT, TG1.MADT
HAVING COUNT(DISTINCT TG1.MAGV) = (SELECT COUNT(*)
									FROM GIAOVIEN GV2
									WHERE GV2.MABM = 'HTTT')

-- Q60. Cho	biết tên đề tài	có tất cả giảng	viên bộ môn	“Hệ thống thông	tin” tham gia		
-- EXCEPT
SELECT DISTINCT DT1.TENDT
FROM DETAI DT1, THAMGIADT TG1
WHERE TG1.MADT = DT1.MADT
	AND NOT EXISTS (SELECT GV2.MAGV
					FROM GIAOVIEN GV2, BOMON BM
					WHERE GV2.MABM = BM.MABM AND BM.TENBM = N'Hệ thống thông tin'
					EXCEPT
					SELECT TG2.MAGV
					FROM THAMGIADT TG2
					WHERE TG2.MADT = TG1.MADT)

-- NOT EXISTS
SELECT DISTINCT DT1.TENDT
FROM DETAI DT1, THAMGIADT TG1
WHERE TG1.MADT = DT1.MADT
	AND NOT EXISTS (SELECT*
					FROM GIAOVIEN GV2, BOMON BM
					WHERE GV2.MABM = BM.MABM AND BM.TENBM = N'Hệ thống thông tin'
						AND NOT EXISTS (SELECT*
									FROM THAMGIADT TG2
									WHERE TG2.MADT = TG1.MADT
										AND TG2.MAGV = GV2.MAGV))
-- COUNT
SELECT DT1.TENDT 
FROM DETAI DT1, THAMGIADT TG1, GIAOVIEN GV1, BOMON BM
WHERE DT1.MADT = TG1.MADT
	AND GV1.MABM = BM.MABM
	AND BM.TENBM = N'Hệ thống thông tin'
	AND GV1.MAGV = TG1.MAGV
GROUP BY DT1.TENDT, TG1.MADT
HAVING COUNT(DISTINCT TG1.MAGV) = (SELECT COUNT(*)
									FROM GIAOVIEN GV2, BOMON BM2
									WHERE GV2.MABM = BM2.MABM
									AND BM2.TENBM = N'Hệ thống thông tin')

-- Q61. Cho	biết giáo viên nào đã tham gia tất cả các đề tài có	mã chủ đề là QLGD.		
-- EXCEPT	
SELECT DISTINCT GV.*
FROM GIAOVIEN GV, THAMGIADT TG1
WHERE GV.MAGV = TG1.MAGV
	AND NOT EXISTS (SELECT DT.MADT
					FROM DETAI DT
					WHERE DT.MACD = 'QLGD'
					EXCEPT
					SELECT TG2.MADT
					FROM THAMGIADT TG2, DETAI DT2
					WHERE TG1.MAGV = TG2.MAGV
					AND TG2.MADT = DT2.MADT
					AND DT2.MACD = 'QLGD')

-- NOT EXISTS 
SELECT DISTINCT GV.*
FROM GIAOVIEN GV, THAMGIADT TG1
WHERE GV.MAGV = TG1.MAGV
	AND NOT EXISTS (SELECT*
					FROM DETAI DT
					WHERE DT.MACD = 'QLGD'
						AND NOT EXISTS (SELECT*
										FROM THAMGIADT TG2
										WHERE TG1.MAGV = TG2.MAGV
											AND TG2.MADT = DT.MADT))
-- COUNT
SELECT GIAOVIEN.*
FROM GIAOVIEN
WHERE MAGV IN ( SELECT GV.MAGV
				FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
				WHERE GV.MAGV = TG.MAGV 
					AND TG.MADT = DT.MADT
					AND DT.MACD = 'QLGD'
				GROUP BY GV.MAGV
				HAVING COUNT(DISTINCT TG.MADT) = ( SELECT COUNT(*)
													FROM DETAI DT1
													WHERE DT1.MACD = 'QLGD' ))

-- Q62. Cho	biết tên giáo viên nào tham	gia	tất	cả các đề tài mà giáo viên Trần	Trà	Hương đã tham gia
-- EXCEPT
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV
	AND NOT EXISTS (SELECT TG1.MADT 
					FROM THAMGIADT TG1, GIAOVIEN GV1
					WHERE GV1.HOTEN = N'Trần Trà Hương'
						AND GV1.MAGV = TG1.MAGV
					EXCEPT
					SELECT TG2.MADT
					FROM THAMGIADT TG2
					WHERE TG2.MAGV = TG.MAGV)
-- NOT EXISTS
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV
	AND NOT EXISTS (SELECT*
					FROM THAMGIADT TG1, GIAOVIEN GV1
					WHERE GV1.HOTEN = N'Trần Trà Hương'
						AND GV1.MAGV = TG1.MAGV
						AND NOT EXISTS (SELECT*
										FROM THAMGIADT TG2
										WHERE TG2.MAGV = TG.MAGV
										AND TG2.MADT = TG1.MADT))
-- COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, GIAOVIEN TTH, THAMGIADT TTH1
WHERE GV.MAGV = TG.MAGV
	AND TTH.HOTEN = N'Trần Trà Hương'
	AND TTH.MAGV = TTH1.MAGV
	AND TG.MADT = TTH1.MADT
GROUP BY TG.MAGV, GV.HOTEN
HAVING COUNT (DISTINCT TG.MADT) = (SELECT COUNT(DISTINCT TG1.MADT)
									FROM THAMGIADT TG1, GIAOVIEN GV1
									WHERE GV1.HOTEN = N'Trần Trà Hương'
										AND GV1.MAGV = TG1.MAGV)
-- Q63. Cho	biết tên đề tài	nào	mà được tất	cả các giáo	viên của bộ môn	Hóa	Hữu	Cơ tham	gia
-- EXCEPT
SELECT DISTINCT DT1.TENDT
FROM DETAI DT1, THAMGIADT TG1
WHERE TG1.MADT = DT1.MADT
	AND NOT EXISTS (SELECT GV2.MAGV
					FROM GIAOVIEN GV2, BOMON BM
					WHERE GV2.MABM = BM.MABM AND BM.TENBM = N'Hóa hữu cơ'
					EXCEPT
					SELECT TG2.MAGV
					FROM THAMGIADT TG2
					WHERE TG2.MADT = TG1.MADT)

-- NOT EXISTS
SELECT DISTINCT DT1.TENDT
FROM DETAI DT1, THAMGIADT TG1
WHERE TG1.MADT = DT1.MADT
	AND NOT EXISTS (SELECT*
					FROM GIAOVIEN GV2, BOMON BM
					WHERE GV2.MABM = BM.MABM AND BM.TENBM = N'Hóa hữu cơ'
						AND NOT EXISTS (SELECT*
									FROM THAMGIADT TG2
									WHERE TG2.MADT = TG1.MADT
										AND TG2.MAGV = GV2.MAGV))
-- COUNT
SELECT DT1.TENDT 
FROM DETAI DT1, THAMGIADT TG1, GIAOVIEN GV1, BOMON BM
WHERE DT1.MADT = TG1.MADT
	AND GV1.MABM = BM.MABM
	AND BM.TENBM = N'Hóa hữu cơ'
	AND GV1.MAGV = TG1.MAGV
GROUP BY DT1.TENDT, TG1.MADT
HAVING COUNT(DISTINCT TG1.MAGV) = (SELECT COUNT(*)
									FROM GIAOVIEN GV2, BOMON BM2
									WHERE GV2.MABM = BM2.MABM
									AND BM2.TENBM = N'Hóa hữu cơ')
-- Q64. Cho biết tên giáo viên nào mà tham gia tất cả các công việc của	đề tài 006.
-- EXCEPT
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV 
	AND NOT EXISTS (SELECT CV.SOTT
					FROM CONGVIEC CV
					WHERE CV.MADT = '006'
					EXCEPT
					SELECT TG1.STT
					FROM THAMGIADT TG1
					WHERE TG1.MADT = '006'
						AND TG1.MAGV = GV.MAGV)
-- NOT EXISTS
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV 
	AND NOT EXISTS (SELECT*
					FROM CONGVIEC CV
					WHERE CV.MADT = '006'
						AND NOT EXISTS (SELECT*
									FROM THAMGIADT TG1
									WHERE TG1.MADT = '006'
										AND TG1.MAGV = GV.MAGV
										AND TG1.STT = CV.SOTT))
-- COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV
	AND TG.MADT = '006'
GROUP BY GV.HOTEN, TG.MAGV
HAVING COUNT(*) = ( SELECT COUNT(*)
					FROM CONGVIEC CV
					WHERE CV.MADT = '006')
-- Q65. Cho	biết giáo viên nào đã tham gia tất cả các đề tài của chủ đề Ứng	dụng công nghệ
-- EXCEPT	
SELECT DISTINCT GV.*
FROM GIAOVIEN GV, THAMGIADT TG1
WHERE GV.MAGV = TG1.MAGV
	AND NOT EXISTS (SELECT DT.MADT
					FROM DETAI DT, CHUDE CD
					WHERE DT.MACD = CD.MACD
						AND CD.TENCD = N'Ứng dụng công nghệ'
					EXCEPT
					SELECT TG2.MADT
					FROM THAMGIADT TG2, DETAI DT2, CHUDE CD2
					WHERE TG1.MAGV = TG2.MAGV
					AND TG2.MADT = DT2.MADT
					AND DT2.MACD = CD2.MACD
					AND CD2.TENCD = N'Ứng dụng công nghệ')

-- NOT EXISTS 
SELECT DISTINCT GV.*
FROM GIAOVIEN GV, THAMGIADT TG1
WHERE GV.MAGV = TG1.MAGV
	AND NOT EXISTS (SELECT*
					FROM DETAI DT, CHUDE CD
					WHERE DT.MACD = CD.MACD
						AND CD.TENCD = N'Ứng dụng công nghệ'
						AND NOT EXISTS (SELECT*
										FROM THAMGIADT TG2
										WHERE TG1.MAGV = TG2.MAGV
											AND TG2.MADT = DT.MADT))
-- COUNT
SELECT GIAOVIEN.*
FROM GIAOVIEN
WHERE MAGV IN ( SELECT GV.MAGV
				FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT, CHUDE CD
				WHERE GV.MAGV = TG.MAGV 
					AND TG.MADT = DT.MADT
					AND DT.MACD = CD.MACD
						AND CD.TENCD = N'Ứng dụng công nghệ'
				GROUP BY GV.MAGV
				HAVING COUNT(DISTINCT TG.MADT) = ( SELECT COUNT(*)
													FROM DETAI DT1, CHUDE CD1
													WHERE DT1.MACD = CD1.MACD
														AND CD1.TENCD = N'Ứng dụng công nghệ' ))

-- Q66. Cho	biết tên giáo viên nào đã tham gia tất cả các đề tài do	Trần Trà Hương làm chủ nhiệm
-- EXCEPT
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV 
	AND NOT EXISTS (SELECT DT.MADT
					FROM DETAI DT, GIAOVIEN GV1
					WHERE GV1.HOTEN = N'Trần Trà Hương'
						AND DT.GVCNDT = GV1.MAGV
					EXCEPT 
					SELECT TG1.MADT
					FROM THAMGIADT TG1
					WHERE TG1.MAGV = GV.MAGV)
-- NOT EXISTS
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV 
	AND NOT EXISTS (SELECT* 
					FROM DETAI DT, GIAOVIEN GV1
					WHERE GV1.HOTEN = N'Trần Trà Hương'
						AND DT.GVCNDT = GV1.MAGV
						AND NOT EXISTS (SELECT*
							FROM THAMGIADT TG1
							WHERE TG1.MAGV = GV.MAGV
								AND TG1.MADT = DT.MADT))
-- COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, GIAOVIEN TTH, DETAI DT
WHERE GV.MAGV = TG.MAGV
	AND TTH.HOTEN = N'Trần Trà Hương'
	AND DT.GVCNDT = TTH.MAGV
	AND TG.MADT = DT.MADT
GROUP BY GV.HOTEN, TG.MAGV
HAVING COUNT (DISTINCT TG.MADT) = (SELECT COUNT(*)
									FROM DETAI DT1, GIAOVIEN TTH1
									WHERE TTH1.HOTEN = N'Trần Trà Hương'
										AND DT1.GVCNDT = TTH1.MAGV)
-- Q67. Cho	biết tên đề tài	nào	mà được	tất	cả các giáo	viên của khoa CNTT tham	gia.
-- EXCEPT
SELECT DISTINCT DT.TENDT
FROM DETAI DT, THAMGIADT TG, GIAOVIEN GV
WHERE DT.MADT = TG.MADT 
	AND GV.MAGV = TG.MAGV
	AND NOT EXISTS (SELECT GV1.MAGV
					FROM BOMON BM1, GIAOVIEN GV1
					WHERE GV1.MABM = BM1.MABM
						AND BM1.MAKHOA = 'CNTT'
					EXCEPT 
					SELECT TG1.MAGV
					FROM THAMGIADT TG1
					WHERE TG1.MADT = TG.MADT)
-- NOT EXISTS
SELECT DISTINCT DT.TENDT
FROM DETAI DT, THAMGIADT TG, GIAOVIEN GV
WHERE DT.MADT = TG.MADT 
	AND GV.MAGV = TG.MAGV
	AND NOT EXISTS (SELECT*
					FROM BOMON BM1, GIAOVIEN GV1
					WHERE GV1.MABM = BM1.MABM
						AND BM1.MAKHOA = 'CNTT'
						AND NOT EXISTS (SELECT*
							FROM THAMGIADT TG1
							WHERE TG1.MADT = TG.MADT
								AND TG1.MAGV = GV1.MAGV))
-- COUNT
SELECT DT.TENDT
FROM DETAI DT, THAMGIADT TG, GIAOVIEN GV, BOMON BM
WHERE DT.MADT = TG.MADT 
	AND GV.MAGV = TG.MAGV
	AND GV.MABM = BM.MABM
	AND BM.MAKHOA = 'CNTT'
GROUP BY DT.TENDT, TG.MADT
HAVING COUNT (DISTINCT TG.MAGV) = ( SELECT COUNT(*) 
									FROM GIAOVIEN GV1, BOMON BM1
									WHERE GV1.MABM = BM1.MABM
										AND BM1.MAKHOA = 'CNTT' )
-- Q68. Cho	biết tên giáo viên nào mà tham gia tất cả các công việc	của	đề tài Nghiên cứu tế bào gốc
-- EXCEPT	
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG1
WHERE GV.MAGV = TG1.MAGV
	AND NOT EXISTS (SELECT CV.SOTT
					FROM DETAI DT, CONGVIEC CV
					WHERE DT.MADT = CV.MADT
						AND DT.TENDT = N'Nghiên cứu tế bào gốc'
					EXCEPT
					SELECT TG2.STT
					FROM THAMGIADT TG2, DETAI DT2
					WHERE TG1.MAGV = TG2.MAGV
						AND TG2.MADT = DT2.MADT
						AND DT2.TENDT = N'Nghiên cứu tế bào gốc')

-- NOT EXISTS 
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG1
WHERE GV.MAGV = TG1.MAGV
	AND NOT EXISTS (SELECT*
					FROM DETAI DT, CONGVIEC CV
					WHERE DT.MADT = CV.MADT
						AND DT.TENDT = N'Nghiên cứu tế bào gốc'
						AND NOT EXISTS (SELECT* 
									FROM THAMGIADT TG2, DETAI DT2
									WHERE TG1.MAGV = TG2.MAGV
										AND TG2.MADT = DT2.MADT
										AND DT2.TENDT = N'Nghiên cứu tế bào gốc'
										AND TG2.STT = CV.SOTT))
-- COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE GV.MAGV = TG.MAGV 
	AND TG.MADT = DT.MADT
	AND DT.TENDT = N'Nghiên cứu tế bào gốc'
GROUP BY TG.MAGV, GV.HOTEN
HAVING COUNT(*) = ( SELECT COUNT(*)
					FROM DETAI DT1, CONGVIEC CV
					WHERE DT1.TENDT = N'Nghiên cứu tế bào gốc'
						AND CV.MADT = DT1.MADT)
-- Q69. Tìm	tên	các	giáo viên được phân	công làm tất cả các	đề tài có kinh phí trên	100	triệu?
-- EXCEPT
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE GV.MAGV = TG.MAGV
	AND DT.KINHPHI > 100
	AND DT.MADT = TG.MADT
	AND NOT EXISTS (SELECT MADT
					FROM DETAI
					WHERE KINHPHI > 100
					EXCEPT
					SELECT TG1.MADT
					FROM THAMGIADT TG1
					WHERE TG1.MAGV = TG.MAGV)
-- NOT EXISTS
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE GV.MAGV = TG.MAGV
	AND DT.KINHPHI > 100
	AND DT.MADT = TG.MADT
	AND NOT EXISTS (SELECT*
					FROM DETAI
					WHERE KINHPHI > 100
					AND NOT EXISTS (SELECT*
									FROM THAMGIADT TG1
									WHERE TG1.MAGV = TG.MAGV
										AND TG1.MADT = DETAI.MADT))
-- COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV
	AND TG.MADT IN (SELECT MADT FROM DETAI WHERE KINHPHI > 100)
GROUP BY TG.MAGV, GV.HOTEN
HAVING COUNT (DISTINCT TG.MADT) = (SELECT COUNT(*)
									FROM DETAI DT
									WHERE DT.KINHPHI > 100)
-- Q70. Cho	biết tên đề tài	nào	mà được	tất	cả các giáo	viên của khoa Sinh Học tham	gia
-- EXCEPT
SELECT DISTINCT DT.TENDT
FROM DETAI DT, THAMGIADT TG, GIAOVIEN GV
WHERE DT.MADT = TG.MADT 
	AND GV.MAGV = TG.MAGV
	AND NOT EXISTS (SELECT GV1.MAGV
					FROM BOMON BM1, GIAOVIEN GV1, KHOA K1
					WHERE GV1.MABM = BM1.MABM
						AND BM1.MAKHOA = K1.MAKHOA
						AND K1.TENKHOA = N'Sinh học'
					EXCEPT 
					SELECT TG1.MAGV
					FROM THAMGIADT TG1
					WHERE TG1.MADT = TG.MADT)
-- NOT EXISTS
SELECT DISTINCT DT.TENDT
FROM DETAI DT, THAMGIADT TG, GIAOVIEN GV
WHERE DT.MADT = TG.MADT 
	AND GV.MAGV = TG.MAGV
	AND NOT EXISTS (SELECT*
					FROM BOMON BM1, GIAOVIEN GV1, KHOA K1
					WHERE GV1.MABM = BM1.MABM
						AND BM1.MAKHOA = K1.MAKHOA
						AND K1.TENKHOA = N'Sinh học'
						AND NOT EXISTS (SELECT*
							FROM THAMGIADT TG1
							WHERE TG1.MADT = TG.MADT
								AND TG1.MAGV = GV1.MAGV))
-- COUNT
SELECT DT.TENDT
FROM DETAI DT, THAMGIADT TG, GIAOVIEN GV, BOMON BM, KHOA K
WHERE DT.MADT = TG.MADT 
	AND GV.MAGV = TG.MAGV
	AND GV.MABM = BM.MABM
	AND BM.MAKHOA = K.MAKHOA
	AND K.TENKHOA = N'Sinh học'
GROUP BY DT.TENDT, TG.MADT
HAVING COUNT (DISTINCT TG.MAGV) = ( SELECT COUNT(*) 
									FROM GIAOVIEN GV1, BOMON BM1, KHOA K1
									WHERE GV1.MABM = BM1.MABM
										AND BM1.MAKHOA = K1.MAKHOA
										AND K1.TENKHOA = N'Sinh học' )
-- Q71. Cho	biết mã	số,	họ tên,	ngày sinh của giáo viên	tham gia tất cả các	công việc của đề tài “Ứng dụng hóa học xanh”.
--EXCEPT
SELECT DISTINCT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV, THAMGIADT TG1
WHERE GV.MAGV = TG1.MAGV
	AND NOT EXISTS (SELECT CV.SOTT
					FROM DETAI DT, CONGVIEC CV
					WHERE DT.MADT = CV.MADT
						AND DT.TENDT = N'Ứng dụng hóa học xanh'
					EXCEPT
					SELECT TG2.STT
					FROM THAMGIADT TG2, DETAI DT2
					WHERE TG1.MAGV = TG2.MAGV
						AND TG2.MADT = DT2.MADT
						AND DT2.TENDT = N'Ứng dụng hóa học xanh')

-- NOT EXISTS 
SELECT DISTINCT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV, THAMGIADT TG1
WHERE GV.MAGV = TG1.MAGV
	AND NOT EXISTS (SELECT*
					FROM DETAI DT, CONGVIEC CV
					WHERE DT.MADT = CV.MADT
						AND DT.TENDT = N'Ứng dụng hóa học xanh'
						AND NOT EXISTS (SELECT* 
									FROM THAMGIADT TG2, DETAI DT2
									WHERE TG1.MAGV = TG2.MAGV
										AND TG2.MADT = DT2.MADT
										AND DT2.TENDT = N'Ứng dụng hóa học xanh'
										AND TG2.STT = CV.SOTT))
-- COUNT
SELECT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE GV.MAGV = TG.MAGV 
	AND TG.MADT = DT.MADT
	AND DT.TENDT = N'Ứng dụng hóa học xanh'
GROUP BY GV.HOTEN, GV.MAGV, GV.NGSINH
HAVING COUNT(*) = ( SELECT COUNT(*)
					FROM DETAI DT1, CONGVIEC CV
					WHERE DT1.TENDT = N'Ứng dụng hóa học xanh'
						AND CV.MADT = DT1.MADT)

-- Q72. Cho	biết mã	số,	họ tên,	tên	bộ môn và tên người	quản lý	chuyên môn của giáo	viên tham gia tất cả các đề tài	thuộc chủ đề “Nghiên cứu phát triển”.-- EXCEPT	
SELECT DISTINCT GV.MAGV, GV.HOTEN, BM.TENBM, QLCM.HOTEN
FROM GIAOVIEN QLCM, GIAOVIEN GV, THAMGIADT TG1, BOMON BM
WHERE GV.MAGV = TG1.MAGV
	AND GV.GVQLCM = QLCM.MAGV
	AND GV.MABM = BM.MABM
	AND NOT EXISTS (SELECT DT.MADT
					FROM DETAI DT, CHUDE CD
					WHERE DT.MACD = CD.MACD
						AND CD.TENCD = N'Nghiên cứu phát triển'
					EXCEPT
					SELECT TG2.MADT
					FROM THAMGIADT TG2, DETAI DT2, CHUDE CD2
					WHERE TG1.MAGV = TG2.MAGV
					AND TG2.MADT = DT2.MADT
					AND DT2.MACD = CD2.MACD
					AND CD2.TENCD = N'Nghiên cứu phát triển')

-- NOT EXISTS 
SELECT DISTINCT GV.MAGV, GV.HOTEN, BM.TENBM, QLCM.HOTEN
FROM GIAOVIEN QLCM, GIAOVIEN GV, THAMGIADT TG1, BOMON BM
WHERE GV.MAGV = TG1.MAGV
	AND GV.GVQLCM = QLCM.MAGV
	AND GV.MABM = BM.MABM
	AND NOT EXISTS (SELECT*
					FROM DETAI DT, CHUDE CD
					WHERE DT.MACD = CD.MACD
						AND CD.TENCD = N'Nghiên cứu phát triển'
						AND NOT EXISTS (SELECT*
										FROM THAMGIADT TG2
										WHERE TG1.MAGV = TG2.MAGV
											AND TG2.MADT = DT.MADT))
-- COUNT
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, QLCM.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT, CHUDE CD, BOMON BM, GIAOVIEN QLCM
WHERE GV.MAGV = TG.MAGV 
	AND TG.MADT = DT.MADT
	AND DT.MACD = CD.MACD
	AND CD.TENCD = N'Nghiên cứu phát triển'
	AND GV.GVQLCM = QLCM.MAGV
	AND GV.MABM = BM.MABM
GROUP BY GV.MAGV, GV.HOTEN, BM.TENBM, QLCM.HOTEN
HAVING COUNT(DISTINCT TG.MADT) = ( SELECT COUNT(*)
									FROM DETAI DT1, CHUDE CD1
									WHERE DT1.MACD = CD1.MACD
									AND CD1.TENCD = N'Nghiên cứu phát triển' )