--Q27
SELECT COUNT(*) SLGV, SUM(LUONG) TONG_LUONG
FROM GIAOVIEN
--Q28
SELECT BOMON.TENBM, COUNT(*) SLGV, AVG(LUONG) LUONG_TRUNG_BINH
FROM GIAOVIEN, BOMON
WHERE GIAOVIEN.MABM = BOMON.MABM
GROUP BY BOMON.MABM, BOMON.TENBM
--Q29
SELECT CHUDE.TENCD, COUNT(*) SLDT
FROM CHUDE, DETAI
WHERE CHUDE.MACD = DETAI.MACD
GROUP BY CHUDE.MACD, CHUDE.TENCD
--Q30
SELECT GV.HOTEN, COUNT(DISTINCT TG.MADT) AS SLDT
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV
GROUP BY GV.MAGV, GV.HOTEN
--Q31
SELECT GV.HOTEN, COUNT(DT.MADT) AS SLDTCN
FROM GIAOVIEN GV, DETAI DT
WHERE GV.MAGV = DT.GVCNDT
GROUP BY GV.MAGV, GV.HOTEN
--Q32
SELECT GV.HOTEN, COUNT(NT.MAGV) AS SLDTCN
FROM GIAOVIEN GV, NGUOITHAN NT
WHERE GV.MAGV = NT.MAGV
GROUP BY GV.MAGV, GV.HOTEN
--Q33
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TG.MADT) >= 3
--Q34
SELECT COUNT(DISTINCT TG.MAGV) SLGV
FROM THAMGIADT TG, DETAI DT
WHERE DT.TENDT = N'Ứng dụng hóa học xanh' AND DT.MADT = TG.MADT
GROUP BY TG.MADT
