--CÂU 01:
SELECT DISTINCT DT.MADT, DT.TENDT
FROM DETAI DT, GIAOVIEN GV_TTH, THAMGIADT TG, GIAOVIEN GV, BOMON BM_CNPM
WHERE GV_TTH.HOTEN = N'Trần Trà Hương' AND GV_TTH.MABM = GV.MABM AND TG.MAGV = GV.MAGV 
	AND DT.GVCNDT = BM_CNPM.TRUONGBM AND BM_CNPM.MABM = 'CNPM' AND TG.MADT = DT.MADT

--CÂU 02:
SELECT DISTINCT CHUDE.*
FROM CHUDE, GIAOVIEN, THAMGIADT, DETAI
WHERE (GIAOVIEN.MABM = 'HTTT' OR GIAOVIEN.MABM = 'CNPM') AND (GIAOVIEN.MAGV = THAMGIADT.MAGV) 
	AND (THAMGIADT.MADT = DETAI.MADT) AND (DETAI.MACD = CHUDE.MACD)

-- TUẦN 02 
-- CÂU 01:
SELECT BM.MABM, BM.TENBM, COUNT(DISTINCT TG.MAGV) AS SLGV
FROM BOMON BM, THAMGIADT TG, DETAI DT, GIAOVIEN GV
WHERE BM.TRUONGBM = DT.GVCNDT AND DT.MADT = TG.MADT AND GV.MABM = BM.MABM AND GV.MAGV = TG.MAGV
GROUP BY BM.MABM, BM.TENBM

--CÂU 02
SELECT GV1.MAGV AS MAGV1, GV2.MAGV AS MAGV2
FROM GIAOVIEN GV1, GIAOVIEN GV2
WHERE GV1.NGSINH = GV2.NGSINH AND GV1.MAGV < GV2.MAGV


﻿